<div style="text-align: center;">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Faculty+Glyphic&display=swap" rel="stylesheet">
    <span style="color: #006FAF; font-size: 20px;">
        <u><strong><em><h2 style="font-family: 'Faculty Glyphic', sans-serif;">EJERCICIOS</h2></em></strong></u>
    </span>
</div>

<div style="text-align: center;">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Faculty+Glyphic&display=swap" rel="stylesheet">
    <span style="color:rgb(0, 0, 0); font-size: 15px;">
        <h2 style="font-family: 'Faculty Glyphic', sans-serif;">Ejercicio 01</h2>
    </span>
</div>

* Crear un array Crear un array 7x8 lleno de ceros de tipo entero.
* Crear un array 7x8 lleno de ceros salvo la primera fila que serán todo unos.
* Crear un array 7x8 lleno de ceros salvo la última fila que será el rango entre 5 y 8.

In [7]:
import numpy as np
# a) Array 7x8 lleno de ceros
array_zeros = np.zeros((7, 8), dtype=int)

print(array_zeros)



[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [4]:
# b) Array 7x8, primera fila de unos
array_primera_fila_unos = np.zeros((7, 8), dtype=int)
array_primera_fila_unos[0, :] = 1
print(array_primera_fila_unos)


[[1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [5]:
# c) Array 7x8, última fila con rango 5 a 8
array_ultima_fila_rango = np.zeros((7, 8), dtype=int)
array_ultima_fila_rango[-1, :4] = np.arange(5, 9)

print(array_ultima_fila_rango)


[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [5 6 7 8 0 0 0 0]]


<div style="text-align: center;">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Faculty+Glyphic&display=swap" rel="stylesheet">
    <span style="color:rgb(0, 0, 0); font-size: 15px;">
        <h2 style="font-family: 'Faculty Glyphic', sans-serif;">Ejercicio 02</h2>
    </span>
</div>

* Crea un vector de 10 elementos, siendo los impares 1 y los pares 2.
* Crea un «tablero de ajedrez» 8x8, con 1 en las casillas negras y 0 en las casillas
blancas.

In [10]:
#Crea un vector de 10 elementos, siendo los impares 1 y los pares 2.
vector_10 = np.array([1 if i % 2 != 0 else 2 for i in range(1, 11)])

print(vector_10)

[1 2 1 2 1 2 1 2 1 2]


In [11]:
#Crea un «tablero de ajedrez» 8x8, con 1 en las casillas negras y 0 en las casillas blancas.
tablero_ajedrez = np.zeros((8, 8), dtype=int)
tablero_ajedrez[1::2, ::2] = 1
tablero_ajedrez[::2, 1::2] = 1
print(tablero_ajedrez)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


<div style="text-align: center;">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Faculty+Glyphic&display=swap" rel="stylesheet">
    <span style="color:rgb(0, 0, 0); font-size: 15px;">
        <h2 style="font-family: 'Faculty Glyphic', sans-serif;">Ejercicio 03</h2>
    </span>
</div>

* Crea una matriz aleatoria 7x7 y halla los valores mínimo y máximo.
* Normaliza la matriz anterior entre 0 y 1.

In [12]:
# Matriz aleatoria 7x7
matriz_random = np.random.rand(7, 7)
valor_min = np.min(matriz_random)
valor_max = np.max(matriz_random)
print(matriz_random)

[[0.85460767 0.21083257 0.78658665 0.283285   0.73571304 0.82710694
  0.83259458]
 [0.40754086 0.93758353 0.66531443 0.46937542 0.95944864 0.3588777
  0.62521797]
 [0.81449399 0.45530572 0.44577024 0.56204972 0.56671623 0.54552092
  0.04622224]
 [0.47396244 0.27296296 0.38145006 0.87423972 0.88333652 0.35367211
  0.35535628]
 [0.69319986 0.55125128 0.92371307 0.84621278 0.31242639 0.76187268
  0.92527941]
 [0.45816409 0.94455372 0.55274368 0.10649969 0.10269521 0.21740598
  0.14681374]
 [0.661159   0.26588734 0.0820243  0.05493156 0.98467862 0.60224673
  0.11058103]]


In [13]:
#Matriz normalizada
matriz_normalizada = (matriz_random - valor_min) / (valor_max - valor_min)
print(matriz_normalizada)

[[0.86139905 0.17540542 0.78891723 0.25260925 0.73470735 0.83209483
  0.83794235]
 [0.38501376 0.94981643 0.65969203 0.45090341 0.97311544 0.33315929
  0.61696606]
 [0.81865473 0.43591102 0.42575022 0.54965525 0.55462779 0.5320425
  0.        ]
 [0.45579125 0.24161029 0.35721194 0.88231856 0.89201192 0.32761232
  0.32940694]
 [0.68940617 0.53814866 0.93503635 0.85245362 0.28366172 0.76258253
  0.93670541]
 [0.43895685 0.95724373 0.53973893 0.06423043 0.06017645 0.18240991
  0.10718825]
 [0.65526408 0.23407066 0.03814995 0.00928048 1.         0.59248837
  0.06857942]]


<div style="text-align: center;">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Faculty+Glyphic&display=swap" rel="stylesheet">
    <span style="color:rgb(0, 0, 0); font-size: 15px;">
        <h2 style="font-family: 'Faculty Glyphic', sans-serif;">Ejercicio 04</h2>
    </span>
</div>

De la siguiente matriz

<div style="text-align: center;">
    <img src="https://user-images.githubusercontent.com/19308295/115969506-dbbc4b00-a502-11eb-9c76-c9da265c5366.png" style="width:300px;">
</div>



Invertir los valores de 9 y 1.

In [15]:
matriz = np.array([
    [1, 1, 1, 1, 1],
    [1, 0, 0, 0, 1],
    [1, 0, 9, 0, 1],
    [1, 0, 0, 0, 1],
    [1, 1, 1, 1, 1]
])

# Invertimos
matriz_invertida = matriz.copy()
matriz_invertida[matriz == 1] = -1  # Marcamos los 1 como -1 temporalmente
matriz_invertida[matriz == 9] = 1   # Reemplazamos 9 por 1
matriz_invertida[matriz_invertida == -1] = 9  # Finalmente los -1 los volvemos 9
print(matriz_invertida)

[[9 9 9 9 9]
 [9 0 0 0 9]
 [9 0 1 0 9]
 [9 0 0 0 9]
 [9 9 9 9 9]]


<div style="text-align: center;">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Faculty+Glyphic&display=swap" rel="stylesheet">
    <span style="color:rgb(0, 0, 0); font-size: 15px;">
        <h2 style="font-family: 'Faculty Glyphic', sans-serif;">Ejercicio 05</h2>
    </span>
</div>

De la siguiente matriz:

<div style="text-align: center;">
    <img src="https://user-images.githubusercontent.com/19308295/115969585-39509780-a503-11eb-92ac-fd88557e6cfc.png"
style="width:300px"></img>
</div>

Extraer las matrices de cada color

In [18]:
matriz_colores = np.arange(1, 31).reshape((6, 5))

# Verde (matriz 3x3 desde (0,1) a (2,3))
verde = matriz_colores[0:3, 1:4]

print(verde)

[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]


In [19]:
# Azul (matriz 2x3 desde (2,0) a (3,2))
azul = matriz_colores[2:4, 0:3]
print(azul)

[[11 12 13]
 [16 17 18]]


In [20]:
# Rojo (tres regiones 2x2)
rojo_1 = matriz_colores[0:2, 3:5]
rojo_2 = matriz_colores[4:6, 3:5]
print(rojo_1)
print(rojo_2)

[[ 4  5]
 [ 9 10]]
[[24 25]
 [29 30]]


<div style="text-align: center;">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Faculty+Glyphic&display=swap" rel="stylesheet">
    <span style="color:rgb(0, 0, 0); font-size: 15px;">
        <h2 style="font-family: 'Faculty Glyphic', sans-serif;">Ejercicio 06</h2>
    </span>
</div>

De la siguiente Matriz:

<div style="text-align: center;">
    <img src="https://user-images.githubusercontent.com/19308295/115969622-613ffb00-a503-11eb-98b8-7edcf70c5851.png"
    style="width:300px"></img>
</DIV>

Se debe **buscar dentro de la matriz de color verde el valor = 50**, luego reemplazar con la pequeña matriz de color celeste quedando la matriz de la siguiente manera:

<div style="text-align: center;">
    <img src="https://user-images.githubusercontent.com/19308295/115969624-656c1880-a503-11eb-9a48-7dba0c379f86.png"
    style="width:300px"></img>
</div>

El algoritmo solución debe poder **ubicar el valor = 50** en cualquier posición y hacer el reemplazo.


In [21]:
# Matriz verde original
matriz = np.array([
    [255, 34, 45, 16, 24, 99],
    [200, 50, 67, 15, 56, 88],
    [165, 67, 34, 26, 87, 70],
    [120, 100, 45, 56, 56, 67],
    [45, 225, 35, 67, 50, 44],
    [36, 255, 24, 78, 77, 23]
])

# Plantilla de reemplazo (celeste)
celeste = np.array([
    [0, 0, 0],
    [0, 255, 0],
    [0, 0, 0]
])

# Función para reemplazar
def reemplazar_valor(matriz, valor, reemplazo):
    m, n = matriz.shape
    rm, rn = reemplazo.shape
    for i in range(1, m-1):
        for j in range(1, n-1):
            if matriz[i, j] == valor:
                matriz[i-1:i+2, j-1:j+2] = reemplazo
    return matriz

# Aplicamos reemplazo para valor = 50
matriz_modificada = matriz.copy()
matriz_modificada = reemplazar_valor(matriz_modificada, 50, celeste)
print(matriz_modificada)

[[  0   0   0  16  24  99]
 [  0 255   0  15  56  88]
 [  0   0   0  26  87  70]
 [120 100  45   0   0   0]
 [ 45 225  35   0 255   0]
 [ 36 255  24   0   0   0]]
