<div style="text-align: center;">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Faculty+Glyphic&display=swap" rel="stylesheet">
    <span style="color: #006FAF; font-size: 20px;">
        <u><strong><em><h2 style="font-family: 'Faculty Glyphic', sans-serif;">DESARROLLO</h2></em></strong></u>
    </span>
</div>

<div style="text-align: left;">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Faculty+Glyphic&display=swap" rel="stylesheet">
    <span style="color: #006FAF; font-size: 17px;">
        <strong><em><h2 style="font-family: 'Faculty Glyphic', sans-serif;">1. Numpy: Funciones básicas</h2></em></strong>
    </span>
</div>

<div style="text-align: left;">
    <span style="font-size: 10px;">
        <strong><em><h1 style="font-family: 'Faculty Glyphic', sans-serif;">Matriz unidimensional</h1></em></strong>
    </span>
</div>

In [11]:
import numpy as np
a=np.array([1,2,3])
print (a)

[1 2 3]


Con la primera instrucción `import numpy as np` le estamos indicando a nuestro programa de Python que de ahora en adelante `np` será la referencia para todo lo referente a NumPy.


<div style="text-align: left;">
    <span style="font-size: 10px;">
        <strong><em><h1 style="font-family: 'Faculty Glyphic', sans-serif;">Matriz bidimensional</h1></em></strong>
    </span>
</div>

In [12]:
b=np.array([(1,2,3),(4,5,6)])
print(b)

[[1 2 3]
 [4 5 6]]


In [16]:
array=np.array([[1,2,3,4],[5,6,7,8]], dtype=np.int64)
print(array)

[[1 2 3 4]
 [5 6 7 8]]


<div style="text-align: left;">
    <span style="font-size: 10px;">
        <strong><em><h1 style="font-family: 'Faculty Glyphic', sans-serif;">Porque usar NumPy</h1></em></strong>
    </span>
</div>

Porque usar NumPy en vez de utilizar las listas propias que ofrece Python para manejar estos datos, la primera razón es que NumPy ocupa menos memoria en comparación a las lista de Python, a su vez es bastante rápido en términos de ejecución. Lo que se observa en el siguiente ejemplo:

<div style="text-align: left;">
    <span style="font-size: 15px;">
        <strong>Cantidad de memoria asignada</strong> 
    </span>
</div>

In [17]:
import sys
S=range(1000)
print(sys.getsizeof(5)*len(S))

28000


In [18]:
D=np.arange(1000)
print(D.size*D.itemsize)

8000


<div style="text-align: left;">
    <span style="font-size: 15px;">
        <strong>Velocidad</strong> 
    </span>
</div>

In [19]:
import time
SIZE = 1000000

L1= range(SIZE)
L2= range(SIZE)

start=time.time()
result=[(x,y) for x,y in zip(L1,L2)]
print((time.time()-start)*1000)

159.1930389404297


In [20]:
A1 = np.arange(SIZE)
A2 = np.arange(SIZE)

start=time.time()
result= A1+A2
print((time.time()-start)*1000)

31.9521427154541


<div style="text-align: left;">
    <span style="font-size: 10px;">
        <strong><em><h1 style="font-family: 'Faculty Glyphic', sans-serif;">Matrices Vacías</h1></em></strong>
    </span>
</div>

En ocasiones se requiere crear matrices vacías, esto se refiere a que se requieren marcadores de posición iniciales, que luego pueden ser rellenados. Se puede inicializar matrices con unos o ceros, pero también puedes hacer matrices que se llenan con valores espaciados uniformemente, valores constantes o aleatorios.


Algunas de las instrucciones para crear este tipo de matrices son las siguientes:

<div style="text-align: left;">
    <span style="font-size: 15px;">
        <strong>Crear una matriz en donde todos los valores sean igual a 1</strong> 
    </span>
</div>

In [21]:
# Crear una matriz  de unos - 3 filas 4 columnas
unos = np.ones((3,4))
print (unos)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


<div style="text-align: left;">
    <span style="font-size: 15px;">
        <strong>Crear una matriz en donde todos los valores sean igual a 0</strong> 
    </span>
</div>

In [22]:
# Crear una matriz de ceros - 3 filas 4 columnas
ceros = np.zeros((3,4))
print (ceros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


<div style="text-align: left;">
    <span style="font-size: 15px;">
        <strong>Crear una matriz de número aleatorios</strong> 
    </span>
</div>

In [23]:
# Crear una matriz con valores aleatorios
aleatorios = np.random.random((2,2))
print (aleatorios)


[[0.02563422 0.02307931]
 [0.09870637 0.27016394]]


<div style="text-align: left;">
    <span style="font-size: 15px;">
        <strong>Crear una matriz vacía</strong> 
    </span>
</div>

In [27]:
# Crear una matriz vacía
vacia = np.empty((3,2))
print(vacia)

[[1.09666385e-311 1.09667971e-311]
 [6.95274672e-310 0.00000000e+000]
 [1.09665502e-311 1.05699581e-307]]


<div style="text-align: left;">
    <span style="font-size: 15px;">
        <strong>Crear una matriz que contenga un solo valor en todas las posiciones</strong> 
    </span>
</div>

In [28]:
# Crear una matriz con un solo valor
full = np.full((2,2),8)
print(full)

[[8 8]
 [8 8]]


<div style="text-align: left;">
    <span style="font-size: 15px;">
        <strong>Crear una matriz con rangos de números</strong> 
    </span>
</div>

In [30]:
# Crear una matriz con valores espaciados uniformemente
espacio1 = np.arange(0,30,5)
print(espacio1)

[ 0  5 10 15 20 25]


In [32]:
espacio2 = np.linspace(0,2,5)
print(espacio2)

[0.  0.5 1.  1.5 2. ]


<div style="text-align: left;">
    <span style="font-size: 15px;">
        <strong>Crear una matriz identidad</strong> 
    </span>
</div>

In [34]:
# Crear una matriz identidad
identidad1 = np.eye(4,4)
print(identidad1)

identidad2 = np.identity(4)
print(identidad2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


<div style="text-align: left;">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Faculty+Glyphic&display=swap" rel="stylesheet">
    <span style="color: #006FAF; font-size: 17px;">
        <strong><em><h2 style="font-family: 'Faculty Glyphic', sans-serif;">2. Inspeccionar matrices de NumPy</h2></em></strong>
    </span>
</div>

<div style="text-align: left;">
    <span style="font-size: 15px;">
        <strong>Dimensión de una matriz</strong> 
    </span>
</div>

In [35]:
# Conocer las dimensiones de una matriz
a = np.array([(1,2,3),(4,5,6)])
print(a.ndim)

2


<div style="text-align: left;">
    <span style="font-size: 15px;">
        <strong>Tipo de Datos en una matriz</strong> 
    </span>
</div>

In [36]:
# Conocer el tipo de los datos
print(a.dtype)


int64


<div style="text-align: left;">
    <span style="font-size: 15px;">
        <strong>Tamaño y forma de una matriz</strong> 
    </span>
</div>

In [37]:
# Conocer el tamaño y forma de la matriz
a = np.array([(1,2,3,4,5,6)])
print(a.size)
print(a.shape)

6
(1, 6)


<div style="text-align: left;">
    <span style="font-size: 15px;">
        <strong>Cambio de forma de una matriz</strong> 
    </span>
</div>

In [38]:
# Cambio de forma de una matriz
a = np.array([(8,9,10),(11,12,13)])
print(a)
a=a.reshape(3,2)
print(a)

[[ 8  9 10]
 [11 12 13]]
[[ 8  9]
 [10 11]
 [12 13]]


<div style="text-align: left;">
    <span style="font-size: 15px;">
        <strong>Seleccionar elemento de una matriz</strong> 
    </span>
</div>

In [41]:
# Extraer un solo valor de la matriz - el valor ubicado en la fila 0 columna
a = np.array([(1,2,3,4),(3,4,5,6)])
print(a[0,2])

3


In [40]:
# Extraer los valores de todas las filas ubicados en la columna 3
a = np.array([(1,2,3,4),(3,4,5,6)])
print(a[0:,2])

[3 5]


<div style="text-align: left;">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Faculty+Glyphic&display=swap" rel="stylesheet">
    <span style="color: #006FAF; font-size: 17px;">
        <strong><em><h2 style="font-family: 'Faculty Glyphic', sans-serif;">3. Operaciones Matemáticas entre matrices de NumPy</h2></em></strong>
    </span>
</div>

<div style="text-align: left;">
    <span style="font-size: 15px;">
        <strong>Valor mínimo, máximo y la suma de una matriz</strong> 
    </span>
</div>

In [42]:
# Encontrar el mínimo, máximo y la suma
a = np.array([2,45,800])
print(a.min())
print(a.max())
print(a.sum())

2
800
847


<div style="text-align: left;">
    <span style="font-size: 15px;">
        <strong>Raiz Cuadrada y Desviación de una matriz</strong> 
    </span>
</div>

In [47]:
# Calcular la raíz cuadrada y la desviación estándar
a = np.array([(1,4,81),(33,44,50,)])
print(np.sqrt(a))
print(np.std(a))

[[1.         2.         9.        ]
 [5.74456265 6.63324958 7.07106781]]
27.5121185419565


<div style="text-align: left;">
    <span style="font-size: 15px;">
        <strong>Suma, resta, multiplicación y división de dos matrices</strong> 
    </span>
</div>

In [48]:
# Calcular la suma, resta, multiplicación y división de dos matrices
x = np.array([(1,2,3),(3,4,5)])
y = np.array([(1,2,3),(3,4,5)])
print(x+y)
print()
print(x-y)
print()
print(x*y)
print()
print(x/y)

[[ 2  4  6]
 [ 6  8 10]]

[[0 0 0]
 [0 0 0]]

[[ 1  4  9]
 [ 9 16 25]]

[[1. 1. 1.]
 [1. 1. 1.]]


<div style="text-align: left;">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Faculty+Glyphic&display=swap" rel="stylesheet">
    <span style="color: #006FAF; font-size: 17px;">
        <strong><em><h2 style="font-family: 'Faculty Glyphic', sans-serif;">EJEMPLOS</h2></em></strong>
    </span>
</div>

<div style="text-align: left;">
    <span style="font-size: 15px;">
        <strong>Ejemplo 1: Cree una matriz de 5x5 con valores 1,2,3,4 justo debajo de la diagonal:
 </strong> 
    </span>
</div>

In [5]:
import numpy as np
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


<div style="text-align: left;">
    <span style="font-size: 15px;">
        <strong>Ejemplo 2: Crea un vector aleatorio de tamaño 30 y encuentra el valor medio :

 </strong> 
    </span>
</div>

In [6]:
Z = np.random.random(30)
m = Z.mean()
print(m)


0.45815659107425816


<div style="text-align: left;">
    <span style="font-size: 15px;">
        <strong>Ejemplo 3: ¿Cómo ordenar una matriz por la enésima columna?:
 </strong> 
    </span>
</div>

In [7]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[3 7 7]
 [2 6 1]
 [6 1 8]]
[[6 1 8]
 [2 6 1]
 [3 7 7]]


<div style="text-align: left;">
    <span style="font-size: 15px;">
        <strong>Ejemplo 4: ¿Cómo agregar un borde (lleno de 0) alrededor de una matriz
 </strong> 
    </span>
</div>

In [8]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
